Repository Jonghakseo/chrome-extension-boilerplate-react-vite, pull requests merged in 2024-06, with the labels that each got.

#493 fix: missing storageMap into useStorage
  packages/shared/lib/hooks/index.ts
  packages/shared/lib/hooks/useStorage.ts
  packages/shared/lib/hooks/useStorage.tsx
Labels: fix

#497 Fix: build error on windows
  chrome-extension/package.json
  package.json
  packages/dev-utils/package.json
  packages/hmr/package.json
  packages/shared/package.json
  packages/storage/package.json
  pages/content-ui/package.json
  pages/content/package.json
  pages/devtools-panel/package.json
  pages/devtools/package.json
  pages/newtab/package.json
  pages/options/package.json
  pages/popup/package.json
  pages/sidepanel/package.json
Labels: fix

#503 fix: Add missing build before dev scripts
  package.json
  packages/dev-utils/package.json
  packages/hmr/package.json
  packages/shared/package.json
  packages/shared/tsup.config.ts
  packages/storage/package.json
  turbo.json
Labels: fix

#517 fix: ignoring files/folders from root .prettierignore by modules
  chrome-extension/package.json
  chrome-extension/public/content.css
  chrome-extension/tsconfig.json
  packages/dev-utils/package.json
  packages/hmr/package.json
  packages/hmr/rollup.config.mjs
  packages/hmr/tsconfig.json
  packages/shared/package.json
  packages/shared/tsconfig.json
  packages/storage/package.json
  packages/storage/tsconfig.json
  pages/content-ui/package.json
  pages/content-ui/src/tailwind-output.css
  pages/content-ui/tsconfig.json
  pages/content/package.json
  pages/content/tsconfig.json
  pages/devtools-panel/package.json
  pages/devtools-panel/postcss.config.js
  pages/devtools-panel/tsconfig.json
  pages/devtools/package.json
  pages/devtools/tsconfig.json
  pages/new-tab/package.json
  pages/new-tab/postcss.config.js
  pages/new-tab/tsconfig.json
  pages/options/package.json
  pages/options/postcss.config.js
  pages/options/src/Options.css
  pages/options/src/index.css
  pages/options/tsconfig.json
  pages/popup/package.json
  pages/popup/postcss.config.js
  pages/popup/tsconfig.json
  pages/side-panel/package.json
  pages/side-panel/postcss.config.js
  pages/side-panel/src/index.html
  pages/side-panel/tsconfig.json
Labels: fix

#518 deps: update pnpm to 9.4.0
  package.json
Labels: dependencies

#513 build(deps): add lint-staged and husky
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: enhancement
