Repository Jonghakseo/chrome-extension-boilerplate-react-vite, pull requests merged in 2024-08, with the labels that each got.

#631 [Docs] Add community section into README.md
  README.md
Labels: documentation

#616 Better firefox support
  package.json
  packages/dev-utils/lib/manifest-parser/impl.ts
  packages/zipper/index.ts
  packages/zipper/lib/zip-bundle/index.ts
  pages/content-runtime/lib/root.tsx
  pages/content-ui/src/index.tsx
  pages/devtools/src/index.ts
  pages/popup/src/Popup.tsx
  turbo.json
Labels: enhancement, high priority

#649 fix: remove unused .tsx files pattern from storage/esbuild
  packages/storage/build.mjs
Labels: enhancement, fix

#613 implement i18n package
  chrome-extension/public/_locales/en/messages.json
  packages/i18n/.eslintignore
  packages/i18n/.gitignore
  packages/i18n/README.md
  packages/i18n/build.dev.mjs
  packages/i18n/build.mjs
  packages/i18n/build.prod.mjs
  packages/i18n/genenrate-i18n.mjs
  packages/i18n/index.ts
  packages/i18n/lib/getMessageFromLocale.ts
  packages/i18n/lib/i18n-dev.ts
  packages/i18n/lib/i18n-prod.ts
  packages/i18n/lib/type.ts
  packages/i18n/locales/en/messages.json
  packages/i18n/locales/ko/messages.json
  packages/i18n/package.json
  packages/i18n/tsconfig.json
  pages/new-tab/package.json
  pages/new-tab/src/NewTab.tsx
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#615 [Docs] Update README.md
  README.md
Labels: documentation

#657 feat/activate eslint import type checking
  .eslintrc
  packages/dev-utils/lib/manifest-parser/impl.ts
  packages/shared/lib/hoc/withSuspense.tsx
  packages/shared/lib/hooks/useStorage.tsx
  packages/storage/lib/exampleThemeStorage.ts
  packages/storage/lib/index.ts
  packages/ui/lib/components/Button.tsx
  packages/ui/lib/utils.ts
  packages/ui/lib/withUI.ts
  packages/ui/tailwind.config.ts
  packages/zipper/index.ts
  pages/devtools-panel/src/Panel.tsx
  pages/popup/src/Popup.tsx
  pages/side-panel/src/SidePanel.tsx
Labels: enhancement

#659 chore/simplify storage
  packages/shared/lib/hooks/useStorage.tsx
  packages/storage/lib/base.ts
  packages/storage/lib/enums.ts
  packages/storage/lib/exampleThemeStorage.ts
  packages/storage/lib/index.ts
  packages/storage/lib/types.ts
Labels: enhancement

#656 chore/simplify hmr
  packages/hmr/lib/constant.ts
  packages/hmr/lib/debounce.ts
  packages/hmr/lib/initClient.ts
  packages/hmr/lib/initReloadServer.ts
  packages/hmr/lib/initializers/initClient.ts
  packages/hmr/lib/initializers/initReloadServer.ts
  packages/hmr/lib/injections/refresh.ts
  packages/hmr/lib/injections/reload.ts
  packages/hmr/lib/interpreter/index.ts
  packages/hmr/lib/interpreter/types.ts
  packages/hmr/lib/plugins/make-entry-point-plugin.ts
  packages/hmr/lib/plugins/watch-public-plugin.ts
  packages/hmr/lib/plugins/watch-rebuild-plugin.ts
  packages/hmr/lib/types.ts
  packages/hmr/package.json
  pnpm-lock.yaml
Labels: enhancement

#664 fix/handle error on injecting script from popup
  pages/popup/src/Popup.tsx
Labels: enhancement, fix

#654 fix/tw-classnames-output-#627
  pages/content-ui/package.json
  pages/content-ui/src/app.tsx
  pages/content-ui/src/index.tsx
  pnpm-lock.yaml
Labels: bug, high priority

#663 deps/pnpm-9.7.1
  package.json
Labels: dependencies

#683 fix: export module error
  packages/tsconfig/base.json
Labels: fix, high priority
