Repository Jonghakseo/chrome-extension-boilerplate-react-vite, pull requests merged in 2024-07, with the labels that each got.

#547 feat: add watchPublicPlugin for Chrome extension #542
  chrome-extension/vite.config.mts
  packages/hmr/lib/plugins/index.ts
  packages/hmr/lib/plugins/watch-public-plugin.ts
  packages/hmr/package.json
  pnpm-lock.yaml
Labels: enhancement

#563 Use turborepo tui
  turbo.json
Labels: fix

#569 Fix #568
  pages/content-ui/package.json
  pages/content-ui/vite.config.mts
Labels: bug

#570 Enahcne: github actions
  .github/workflows/build-zip.yml
  .github/workflows/lint.yml
Labels: enhancement

#581 feat: add 'clean:node_modules' and 'clean:install' commands
  package.json
Labels: enhancement

#599 fix: chrome reference error when use storage in ui package
  packages/storage/build.mjs
  packages/storage/lib/base.ts
  packages/storage/package.json
  packages/vite-config/lib/withPageConfig.mjs
Labels: fix

#614 [Enhance] Add pull request template
  .github/pull_request_template.md
Labels: enhancement
