Repository Jonghakseo/chrome-extension-boilerplate-react-vite, pull requests merged in 2025-05, with the labels that each got.

#976 feat: enable daemon for turbo.json
  turbo.json
Labels: fix

#846 feat: Create plugin for resolve multiple entry points for content and content-ui scripts
  README.md
  chrome-extension/manifest.ts
  package.json
  packages/hmr/lib/plugins/index.ts
  packages/hmr/lib/plugins/make-entry-point-plugin.ts
  packages/hmr/lib/plugins/watch-rebuild-plugin.ts
  packages/hmr/package.json
  packages/i18n/locales/en/messages.json
  packages/i18n/locales/ko/messages.json
  packages/module-manager/README.md
  packages/module-manager/lib/const.ts
  packages/module-manager/lib/helpers/utils.ts
  packages/shared/lib/utils/index.ts
  packages/shared/lib/utils/init-app-with-shadow.ts
  packages/vite-config/lib/build-content-script.ts
  packages/vite-config/lib/get-content-script-entires.ts
  packages/vite-config/lib/index.ts
  packages/vite-config/tailwind.d.ts
  packages/vite-config/tsconfig.json
  pages/content-runtime/README.md
  pages/content-runtime/build.mts
  pages/content-runtime/package.json
  pages/content-runtime/src/App.tsx
  pages/content-runtime/src/index.ts
  pages/content-runtime/src/matches/all/App.tsx
  pages/content-runtime/src/matches/all/index.css
  pages/content-runtime/src/matches/all/index.tsx
  pages/content-runtime/src/matches/example/App.tsx
  pages/content-runtime/src/matches/example/index.css
  pages/content-runtime/src/matches/example/index.tsx
  pages/content-runtime/tailwind.config.ts
  pages/content-runtime/tailwind.d.ts
  pages/content-runtime/tsconfig.json
  pages/content-runtime/vite.config.mts
  pages/content-ui/README.md
  pages/content-ui/build.mts
  pages/content-ui/package.json
  pages/content-ui/src/index.tsx
  pages/content-ui/src/matches/all/App.tsx
  pages/content-ui/src/matches/all/index.css
  pages/content-ui/src/matches/all/index.tsx
  pages/content-ui/src/matches/example/App.tsx
  pages/content-ui/src/matches/example/index.css
  pages/content-ui/src/matches/example/index.tsx
  pages/content-ui/tailwind.d.ts
  pages/content-ui/tsconfig.json
  pages/content-ui/vite.config.mts
  pages/content/README.md
  pages/content/build.mts
  pages/content/package.json
  pages/content/src/index.ts
  pages/content/src/matches/all/index.ts
  pages/content/src/matches/example/index.ts
  pages/content/tsconfig.json
  pages/content/vite.config.mts
  pages/popup/src/Popup.tsx
  pnpm-lock.yaml
  tests/e2e/specs/page-content-runtime.test.ts
  tests/e2e/specs/page-content-ui.test.ts
  tests/e2e/specs/page-content.test.ts
Labels: enhancement

#994 Module manager test
  .github/workflows/e2e-modular.yml
  .github/workflows/e2e.yml
  tests/e2e/specs/page-content-runtime.test.ts
Labels: enhancement

#1007 Release v0.5.1
  .github/secret_scanning.yml
  .github/workflows/prettier.yml
Labels: fix, high priority
